configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/onederful%2Fonederful-dentistry-api-test-f84d84b92a379bdbedff2df080db8ae7f55c372bba5f8e0f3fb85ba6919b7a25.yml
